nginx:
  httpPort: 80
  httpsPort: 443

  sites:
    - name: test
      domain: test.com
      aliases:
        - test.com
        - www.test.com
      proxy:
        type: upstream
        upstream:
          name: test-backend
          servers:
            - name: a
              host: 127.0.0.1
              port: 8080
              weight: 1
            - name: b
              host: 127.0.0.1
              port: 8082
              weight: 1
