- name: be sure ntp is installed
  apt:
    name: ntp
    state: present
  tags:
    - ntp
    - install

- name: be sure ntpd is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
  tags:
    - ntp
    - restart
    - service
